import { S3Profile, ProviderType } from '../../s3/s3Manager'

export type FieldType = 'text' | 'password' | 'toggle'

export interface FormField {
	key: keyof S3Profile
	label: string
	placeholder: string
	note: string
	required: boolean
	defaultValue?: string | boolean
	type?: FieldType
}

export const PROVIDER_MANIFEST: Record<ProviderType, FormField[]> = {
	'cloudflare-r2': [
		{
			key: 'name',
			label: '配置名称',
			placeholder: '例如：我的博客图床',
			note: '给你自己看的一个友好名称。',
			required: true,
		},
		{
			key: 'endpoint',
			label: 'Endpoint',
			placeholder: '<ACCOUNT_ID>.r2.cloudflarestorage.com',
			note: '必需。来自 R2 仪表盘，不含 bucket 路径。',
			required: true,
		},
		{
			key: 'bucketName',
			label: 'Bucket',
			placeholder: '例如：my-bucket',
			note: '必需。R2 存储桶名称。',
			required: true,
		},
		{
			key: 'accessKeyId',
			label: 'Access Key ID',
			placeholder: '请输入 Access Key ID',
			note: '必需。R2 API 密钥。',
			required: true,
		},
		{
			key: 'secretAccessKey',
			label: 'Secret Access Key',
			placeholder: '请输入 Secret Access Key',
			note: '必需。R2 API 密钥。',
			required: true,
			type: 'password',
		},
		{
			key: 'region',
			label: 'Region',
			placeholder: 'auto',
			note: 'R2 必须填 auto。',
			required: true,
			defaultValue: 'auto',
		},
		{
			key: 'useSSL',
			label: 'Use SSL',
			placeholder: '',
			note: '建议开启。',
			required: true,
			defaultValue: true,
			type: 'toggle',
		},
		{
			key: 'baseUrl',
			label: 'Public Base URL',
			placeholder: 'https://<bucket>.r2.dev 或你的自定义域',
			note: '用于拼接可访问链接，不用于 API。',
			required: false,
		},
		{
			key: 'keyPrefix',
			label: 'Key Prefix',
			placeholder: 'images/ 或 yyyy/mm/dd/',
			note: '对象键前缀，可选。',
			required: false,
		},
		{
			key: 'cacheControl',
			label: 'Cache-Control',
			placeholder: 'public, max-age=31536000, immutable',
			note: 'HTTP 缓存头，用于离线访问，默认为一年。',
			required: false,
			defaultValue: 'public, max-age=31536000, immutable',
		},
	],
	minio: [
		{
			key: 'name',
			label: '配置名称',
			placeholder: '例如：本地测试 MinIO',
			note: '给你自己看的一个友好名称。',
			required: true,
		},
		{
			key: 'endpoint',
			label: 'Endpoint',
			placeholder: 'http://127.0.0.1:9000',
			note: '必需。注意包含 http:// 或 https://，且使用 path-style。',
			required: true,
		},
		{
			key: 'bucketName',
			label: 'Bucket',
			placeholder: '例如：obsidian-vault',
			note: '必需。MinIO 存储桶名称。',
			required: true,
		},
		{
			key: 'accessKeyId',
			label: 'Access Key',
			placeholder: '例如：minioadmin',
			note: '必需。你的 MinIO 用户名。',
			required: true,
		},
		{
			key: 'secretAccessKey',
			label: 'Secret Key',
			placeholder: '例如：minioadmin',
			note: '必需。你的 MinIO 密码。',
			required: true,
			type: 'password',
		},
		{
			key: 'region',
			label: 'Region',
			placeholder: 'us-east-1',
			note: '可为任意合法字符串，默认 us-east-1。',
			required: true,
			defaultValue: 'us-east-1',
		},
		{
			key: 'useSSL',
			label: 'Use SSL',
			placeholder: '',
			note: '与 endpoint 协议保持一致。',
			required: true,
			defaultValue: false,
			type: 'toggle',
		},
		{
			key: 'baseUrl',
			label: 'Public Base URL',
			placeholder: '可为空',
			note: '用于拼接可访问链接，不用于 API。',
			required: false,
		},
		{
			key: 'keyPrefix',
			label: 'Key Prefix',
			placeholder: 'images/ 或 yyyy/mm/dd/',
			note: '对象键前缀，可选。',
			required: false,
		},
		{
			key: 'cacheControl',
			label: 'Cache-Control',
			placeholder: 'public, max-age=31536000, immutable',
			note: 'HTTP 缓存头，用于离线访问，默认为一年。',
			required: false,
			defaultValue: 'public, max-age=31536000, immutable',
		},
	],
	'aws-s3': [
		{
			key: 'name',
			label: '配置名称',
			placeholder: '例如：AWS 正式环境',
			note: '给你自己看的一个友好名称。',
			required: true,
		},
		{
			key: 'endpoint',
			label: 'Endpoint',
			placeholder: 'https://s3.amazonaws.com 或区域端点',
			note: '可选。通常无需填写，保持空值由 SDK 处理。',
			required: false,
		},
		{
			key: 'bucketName',
			label: 'Bucket',
			placeholder: '例如：my-bucket',
			note: '必需。AWS S3 存储桶名称。',
			required: true,
		},
		{
			key: 'accessKeyId',
			label: 'Access Key ID',
			placeholder: 'AKIA...',
			note: '必需。',
			required: true,
		},
		{
			key: 'secretAccessKey',
			label: 'Secret Access Key',
			placeholder: '********',
			note: '必需。',
			required: true,
			type: 'password',
		},
		{
			key: 'region',
			label: 'Region',
			placeholder: 'us-east-1',
			note: '必填，必须为合法区域。',
			required: true,
		},
		{
			key: 'useSSL',
			label: 'Use SSL',
			placeholder: '',
			note: '建议开启。',
			required: true,
			defaultValue: true,
			type: 'toggle',
		},
		{
			key: 'baseUrl',
			label: 'Public Base URL',
			placeholder: '可为空或自定义域',
			note: '用于拼接可访问链接，不用于 API。',
			required: false,
		},
		{
			key: 'keyPrefix',
			label: 'Key Prefix',
			placeholder: 'images/ 或 yyyy/mm/dd/',
			note: '对象键前缀，可选。',
			required: false,
		},
		{
			key: 'cacheControl',
			label: 'Cache-Control',
			placeholder: 'public, max-age=31536000, immutable',
			note: 'HTTP 缓存头，用于离线访问，默认为一年。',
			required: false,
			defaultValue: 'public, max-age=31536000, immutable',
		},
	],
	custom: [
		{
			key: 'name',
			label: '配置名称',
			placeholder: '例如：自定义兼容 S3',
			note: '给你自己看的一个友好名称。',
			required: true,
		},
		{
			key: 'endpoint',
			label: 'Endpoint',
			placeholder: 'https://s3.example.com',
			note: '必需。兼容 S3 的端点，通常需要 http(s)://。',
			required: true,
		},
		{
			key: 'bucketName',
			label: 'Bucket',
			placeholder: 'my-bucket',
			note: '必需。',
			required: true,
		},
		{
			key: 'accessKeyId',
			label: 'Access Key ID',
			placeholder: 'AKIA... 或其他',
			note: '必需。',
			required: true,
		},
		{
			key: 'secretAccessKey',
			label: 'Secret Access Key',
			placeholder: '********',
			note: '必需。',
			required: true,
			type: 'password',
		},
		{
			key: 'region',
			label: 'Region',
			placeholder: 'us-east-1',
			note: '可选，留空则默认 us-east-1。',
			required: false,
		},
		{
			key: 'useSSL',
			label: 'Use SSL',
			placeholder: '',
			note: '与 endpoint 协议保持一致。',
			required: true,
			defaultValue: true,
			type: 'toggle',
		},
		{
			key: 'baseUrl',
			label: 'Public Base URL',
			placeholder: '可为空或自定义域',
			note: '用于拼接可访问链接，不用于 API。',
			required: false,
		},
		{
			key: 'keyPrefix',
			label: 'Key Prefix',
			placeholder: 'images/ 或 yyyy/mm/dd/',
			note: '对象键前缀，可选。',
			required: false,
		},
		{
			key: 'cacheControl',
			label: 'Cache-Control',
			placeholder: 'public, max-age=31536000, immutable',
			note: 'HTTP 缓存头，用于离线访问，默认为一年。',
			required: false,
			defaultValue: 'public, max-age=31536000, immutable',
		},
	],
}
